### PR TITLE
Add ECP portal documentation for the new registry management feature

### PR DESCRIPTION
**Pull request by Jianghai-Quantil**
@snikitin-qtl We just add some pages to ECP portal documentation for our new registry management feature. There are some minor edits to existing pages as well. Pls review.

### CODE REVIEW

**Comment by marcfishelquantil** [comment]
@Jianghai-Quantil Neil, can I merge this PR, please?

**Comment by neilyjh** [comment]
@marcfishelquantil I've requested Sergey to merge the PR. Please leave it to him. 
I believe we agreed that requests to merge commits into `master` shall be approved by Sergey.

**Comment by marcfishelquantil** [comment]
Excellent, Neil. That is why I pinged you, as I want to tread carefully. Best regards.

**Review by snikitin-qtl — APPROVED** [review]
Looks good to try it in production!

**Pull request merged**
