### PR TITLE
Update portal docs as per new releases

### PR DESCRIPTION
**Pull request by Jianghai-Quantil**
This PR contains the following updates:
1. Change the contents as per new releases of portal
2. Replace images with high resolution screenshots
3. Reorganize the menus of Application management features
4. Correct typos

@nixoz @snikitin-qtl Please help review.

### CODE REVIEW

**Review by snikitin-qtl — CHANGES_REQUESTED** [review]
Everything looks good to me, but one thing.
The new files are not following the same naming convention. at least let's stick to the lower-kebab-case. Please refer to the deleted filenames.

**Comment by Jianghai-Quantil** [comment]
> Everything looks good to me, but one thing.
> The new files are not following the same naming convention. at least let's stick to the lower-kebab-case. Please refer to the deleted filenames.

@marcfishelquantil Can you look at this and make the change accordingly? The file names of the new screenshots are not following the same naming convention, as Sergey comments above. Please change the file names, and make sure that the links to those files are not broken. After you complete the change, please submit a new PR, then I'll merge `marc-dev` into `dev`.

**Comment by Jianghai-Quantil** [comment]
@snikitin-qtl The images have been renamed to use lower kebab case via this pull request https://github.com/mileweb/docs-content-ecp/pull/18. Please review again.

**Review by snikitin-qtl — APPROVED** [review]
Looks good. Let's give it a try.

**Comment by Jianghai-Quantil** [comment]
> Looks good. Let's give it a try.

@snikitin-qtl Are you going to merge this PR sometime later?

**Comment by snikitin-qtl** [comment]
@Jianghai-Quantil don't you have right to do the merge? I believe you can do it if it is approved. Please give me know if you have issues with that. I will merge

**Comment by Jianghai-Quantil** [comment]
@snikitin-qtl Yes, I have the right to merge the PR by myself. I was just thinking if we shall let whoever reviews and approves a PR hit the button to merge. On this previous PR https://github.com/mileweb/docs-content-ecp/pull/13, you did the merge. 
Anyway, I see what you mean. Let me merge the PR by myself.

**Pull request merged**
